[versions]

[libraries]
findbugs = { module = "com.google.code.findbugs:jsr305", version = "3.0.2" }
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version = "26.0.2" }
lombok = { module = "org.projectlombok:lombok", version = "1.18.38" }
commonsHttpclient = { module = "net.lenni0451.commons:httpclient", version = "1.9.1" }
optconfig = { module = "net.lenni0451:optconfig", version = "1.1.1" }
json = { module = "org.json:json", version = "20250517" }
jda = { module = "net.dv8tion:JDA", version = "6.0.0-preview" }
log4j = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version = "2.25.1" }
sqliteJdbc = { module = "org.xerial:sqlite-jdbc", version = "3.50.3.0" }
bucket4j = { module = "com.bucket4j:bucket4j_jdk17-core", version = "8.15.0" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version = "3.2.2" }

[bundles]

[plugins]
